# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Remote Friendly
email: jeremyzilar@gmail.com
description: "We help small to medium-size organizations transition to remote working."
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://remote-team.work/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jeremyzilar
github_username:  jeremyzilar

# Build settings
markdown: kramdown
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji

include: ["_pages"]
permalink: /:title/

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      image: /assets/img/card-remote-team-work-1.png

collections:
  pages:
    output: true
    permalink: /:path

github:
  organization:
  repository: remotework.team
  default_branch: master

hero__heading: "We help small to medium size organizations transition to remote working."
hero__callout: "Strategic business consulting to help organizations transition to a remote-first work culture and empower teams to have greater productivity and independence."

# Verify ownership in Google webmaster tools
webmaster_verifications:
  google: HIgE8U5i5ucDEtKdW4BBv_l5382H3BMZWgv5wRgZnFc
  # bing: 1234
  # alexa: 1234
  # yandex: 1234
  # baidu: 1234


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
